### ISSUE TITLE
README wrong bandge

### ISSUE THREAD

**Issue by ozanerturk** [eserozvataf/festjs#5]
This repository uses badge from the fork of mine, It has to be changed as 

`![Node.js CI](https://github.com/eserozvataf/festjs/workflows/Node.js%20CI/badge.svg)`

I cannot create a pull request for this because It has to be done in this repository

**Comment by eser** [comment]
Fixed! Thanks.

https://github.com/eserozvataf/festjs/commit/dc28d42326dbafa9f26af947a39bcb3a5a1e7cf9
